spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/flores_eternas_lp
spring.datasource.username=postgres
spring.datasource.password=roottoor
spring.jpa.hibernate.ddl-auto=update
